import { NextPage } from "next";
import Head from "next/head";

const New: NextPage = () => {
  return (
    <div className="container flex flex-col">
      <Head>
        <title>New</title>
      </Head>
      <h1>New1</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New</h1>
      <h1>New10</h1>
    </div>
  );
};

export default New;
